### PR TITLE
Create bjn.yaml

### PR DESCRIPTION
**Pull request by mahalisyarifuddin**
Add Banjar language

### CODE REVIEW

**Comment by kontur** [comment]
hey @mahalisyarifuddin thanks for this addition! looks good to me, but question to you who I think is familiar with the language: do you think an orthography in Jawi should be added as well for completeness? It, too, could inherit and be marked as `secondary` if that is more appropriate.

**Comment by mahalisyarifuddin** [comment]
Indeed, the language has historically used the Jawi script. However, I fear I don't have access to manuscripts or an established, standardized/widespread Jawi orthography for the language. For the moment, let's consider the status as `preliminary`.

**Comment by kontur** [comment]
Okay, roger, I'll add a second orthography then for Jawi or a note as a reminder 👍

**Comment by kontur** [comment]
Thanks again, and sorry for the long wait. This has been merged and will be released shortly.

**Pull request merged**
