### PR TITLE
Add Rōmaji to Japanese

### PR DESCRIPTION
**Pull request by ctrlcctrlv**

### CODE REVIEW

**Comment by macnmm** [comment]
Just wondering about the selection of letters in this change-- should it be limited to those used in Romaji (e.g. exclude x, c etc)?

**Comment by MrBrezina** [comment]
Thank you. Yes, I would exclude `x, c`. What else? Can you update it. Can you add a note if this corresponds to Hepburn or other romanization of Japanese?

https://en.wikipedia.org/wiki/Hepburn_romanization

**Comment by ctrlcctrlv** [comment]
Force pushed, thanks. Removed `x`, `c`, `q`.

**Comment by MrBrezina** [comment]
Thank you, I have merged this into dev for now. Notice that I changed the status to `transliteration`. cc: @sergiolmartins

**Pull request merged**
